/**
 * ConfLiveApplicationEvent.js
 *
 * @description :: TODO: You might write a short summary of how this model works and what it represents here.
 * @docs        :: http://sailsjs.org/#!documentation/models
 */

module.exports = {

    attributes: {

        name: {
            type: 'string'
        },

        data: {
            type: 'json'
        },
        
        token: {
            type: 'integer',
            index: true
        },

        conference: {
            model: 'ConfConference',
            index: true,
            required: true
        },

        expire: {
            type: 'datetime',
            index: true
        },

        toJSON: function() {
            var obj = this.toObject();

            obj.id = obj.token;

            delete obj.conference;
            delete obj.token;
            delete obj.createdAt;
            delete obj.updatedAt;
            obj.toJSON = null;
            return obj;
        }
    },

    afterCreate: function(values, next) {

        // After create, refresh model to get value generated by MySQL trigger
        ConfLiveApplicationEvent
            .findOne( values.id )
            .exec(
                function( err, model ) {
                    if( !err && model ) {

                        // Set the value of the token
                        values.token = model.token;
                    }

                    next( err );
                } );
    }
};
